# -------------------
# Mongodb statefulset
# -------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-dynamic-volume
spec:
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb-dynamic-volume
        image: mongo:4.0.8
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: intelliflash-csi-file-driver-pvc-mongodb-dynamic
          readOnly: false
