# ------------------------------------------------------------------------------------------
# IntelliFlash CSI Driver - Persistent Volume Claim cloned from another PVC
# ------------------------------------------------------------------------------------------

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: intelliflash-csi-file-driver-pvc-nginx-dynamic-clone
spec:
  storageClassName: intelliflash-csi-file-driver-cs-nginx-dynamic
  dataSource:
    kind: PersistentVolumeClaim
    apiGroup: ""
    name: intelliflash-csi-file-driver-pvc-nginx-dynamic # pvc name
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---

# ---------
# Nginx pod
# ---------

apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic-volume-clone
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: intelliflash-csi-file-driver-data-clone
  volumes:
    - name: intelliflash-csi-file-driver-data-clone
      persistentVolumeClaim:
        claimName: intelliflash-csi-file-driver-pvc-nginx-dynamic-clone
        readOnly: false
