# Pod using pre-created nginx-dynamic-volume

# ---------
# Nginx pod
# ---------

apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic-volume
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: intelliflash-csi-file-driver-data
  volumes:
    - name: intelliflash-csi-file-driver-data
      persistentVolumeClaim:
        claimName: intelliflash-csi-file-driver-pvc-nginx-dynamic
        readOnly: false
