# Create a new snapshot class
#
# !!! Make sure to run nginx-persistent-volume.yaml before running this example
#
# $ kubectl apply -f examples/kubernetes/snapshot-class.yaml
#

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: intelliflash-csi-file-snapshot-class
driver: intelliflash-csi-file-driver.intelliflash.com
deletionPolicy: Delete
# parameters:
#   csiSnapshotterSecretName: csi-secret
#   csiSnapshotterSecretNamespace: csi-namespace
#   TODO add "dataset" parameter support
