# Take a new snapshot
#
# !!! Make sure to run nginx-persistent-volume.yaml before running this example
# !!! Make sure to run snapshot-class.yaml before running this example
#
# $ kubectl apply -f examples/kubernetes/take-snapshot.yaml
#

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-test
spec:
  volumeSnapshotClassName: intelliflash-csi-file-snapshot-class
  source:
    persistentVolumeClaimName: intelliflash-csi-file-driver-pvc-nginx-persistent
